spring.application.name=MultiDBProject
server.port=8484

# MySQL Configuration
db1.datasource.jdbc-url=jdbc:mysql://localhost:3306/finishers
db1.datasource.username=root
db1.datasource.password=shub
db1.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# PostgreSQL Configuration
db2.datasource.jdbc-url=jdbc:postgresql://localhost:5432/finishers
db2.datasource.username=postgres
db2.datasource.password=your_postgres_password
db2.datasource.driver-class-name=org.postgresql.Driver
